name: Build Android and iOS
on: [ pull_request, push ]
jobs:
  npm-installs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Installing NodeJS
        with:
          node-version: '16'
      - name: Cache npm dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
  pods-installs:
    runs-on: macos-latest
    needs: npm-installs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache Cocoapod dependencies
        id: pods
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Cache npm dependencies
        if: steps.pods.outputs.cache-hit != 'true'
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install pod dependencies
        if: steps.pods.outputs.cache-hit != 'true'
        working-directory: ./ios
        run: pod install
  build-android:
    needs: npm-installs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Installing NodeJS
        with:
          node-version: '16'
      - name: Cache npm dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Build Android Release
        working-directory: ./android
        run: ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-ios:
    needs: pods-installs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Installing NodeJS
        with:
          node-version: '16'
      - name: Cache npm dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        name: Cache Cocoapod dependencies
        id: pods
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Build app
        working-directory: ./ios
        run: xcodebuild -workspace diversity_app.xcworkspace -scheme diversity_app clean archive -sdk iphoneos -configuration Debug -UseModernBuildSystem=NO -archivePath $PWD/diversity_app CODE_SIGNING_ALLOWED=NO
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/
